---
- hosts: dev
  connection: ssh

  tasks:
    - name: getting the url in clcdn.appache.org
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
        dest: "/root/"

    - name: untar the url
      command: tar -zxvf apache-tomcat-9.0.71.tar.gz

    - name: rename file
      command: mv apache-tomcat-9.0.71.tar.gz tomcat

    - name: edit contxt.xml
      template:
         src: context.xml
         dest: /root/tomcat/webapps/META-INF/context.xml

    - name: edit tomcat-users.xml
       src: tomcat-users.xml
       dest: /root/tomcat/conf/tomcat-users.xml
       
    - name: edit server.xml
       src: server.xml
       dest: /root/tomcat/conf/server.xml
       
    - name: start tomcat webserver
      shell: nohup /root/tomcat/bin/startup.sh
